In [1]:
#!pip install pymongo

In [2]:
#from pymongo import MongoClient
import pandas as pd

In [3]:
# # Connect to MongoDB via forwarded port
# client = MongoClient(
#     "mongodb://localhost:8888/"
#     "?directConnection=true"
# )

# # Access your database and collection
# db = client["aeroclouddb"]
# collection = db["flights"]

# Fetch some data
#data = list(collection.find())

#df = pd.DataFrame(data)

df1 =  pd.read_csv('Datasets/augmented_SRQ_data_v3.csv')
df2 =  pd.read_csv('Datasets/aeroclouddb.flights.csv')

df1['flight_number_clean'] = df1['Flight'].str[2:]
df1['Date'] = pd.to_datetime(df1['Date'])

df2['Date'] = pd.to_datetime(df2['scheduled_date'])
df2['Date'] = df2['Date'].dt.strftime('%Y-%m-%d')

flights_df = df1.copy()
extra_info_df= df2.copy()

flights_df

C:\Users\KamarioSinclair\AppData\Local\Temp\ipykernel_17376\126686138.py:17: DtypeWarning: Columns (3,11,12,13,14,21,22,23,24,28,34,35,36,37,38,39,47,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,86,99,100,104,105,106,108,109,116,118,122,123,127,128,129,130,131,132,133,134,137,141,142,143,144,147,148,149,150,151,152,153,159,160,161,162,163,164,166,167,168,169,170,171,172,173,174,175,185,186,187,188,191,192,206) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 =  pd.read_csv('Datasets/aeroclouddb.flights.csv')

,Unnamed: 0,Date,Flight,Destination Airport,Airline,Boarded,Day_of_Week,Month,Day_of_Month,Destination Airport_encoded,...,day_sin,day_cos,month_sin,month_cos,dow_sin,dow_cos,route_mean,route_median,route_std,flight_number_clean
0,0,2023-09-14,AA2679,DFW,AA,130,3,9,14,23,...,0.299363,-0.954139,-8.660254e-01,-0.5,0.433884,-0.900969,96.518750,99.5,51.749150,2679
1,1,2023-09-14,G41150,PIT,G4,155,3,9,14,60,...,0.299363,-0.954139,-8.660254e-01,-0.5,0.433884,-0.900969,148.430034,162.0,34.409989,1150
2,2,2023-09-14,G4183,ABE,G4,152,3,9,14,0,...,0.299363,-0.954139,-8.660254e-01,-0.5,0.433884,-0.900969,150.730769,157.0,23.763546,183
3,3,2023-09-14,G4218,AVL,G4,144,3,9,14,6,...,0.299363,-0.954139,-8.660254e-01,-0.5,0.433884,-0.900969,126.549550,133.5,33.820457,218
4,4,2023-09-14,G42977,CAK,G4,143,3,9,14,14,...,0.299363,-0.954139,-8.660254e-01,-0.5,0.433884,-0.900969,152.762452,160.0,22.801929,2977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12555,12555,2025-07-20,WN4409,IND,WN,71,6,7,20,40,...,-0.790776,-0.612106,1.224647e-16,-1.0,-0.781831,0.623490,105.357143,111.0,35.060103,4409
12556,12556,2025-07-20,WN4605,MDW,WN,125,6,7,20,49,...,-0.790776,-0.612106,1.224647e-16,-1.0,-0.781831,0.623490,120.400000,122.0,39.266401,4605
12557,12557,2025-07-20,WN4606,STL,WN,75,6,7,20,71,...,-0.790776,-0.612106,1.224647e-16,-1.0,-0.781831,0.623490,119.448980,128.0,35.404741,4606
12558,12558,2025-07-20,XP306,HVN,XP,132,6,7,20,36,...,-0.790776,-0.612106,1.224647e-16,-1.0,-0.781831,0.623490,121.601604,129.0,37.176401,306
12559,12559,2025-07-21,G41875,AVL,G4,113,0,7,21,6,...,-0.897805,-0.440394,1.224647e-16,-1.0,0.000000,1.000000,126.549550,133.5,33.820457,1875

In [4]:
extra_info_df

,_id,flight_id,scheduled_date,flight_number,flight_type,operator_name,operator,aircraft_type_code,aircraft_type,registration,...,interfacePriority.baggage_belt_new_2,interfacePriority.baggage_belt_new_3,interfacePriority.baggage_belt_tues,baggage_belt_new_2,baggage_belt_new_3,baggage_belt_tues,interfacePriority.flight_stop_names,interfacePriority.flight_stop_codes,interfacePriority.country,Date
0,6489dd39cc5ce30f8f2edea6,DL2997:ATL:A:2023-06-14T04:15:00.000Z,2023-06-14T04:15:00.000Z,2997,J,Delta Air Lines,DL,75W,BOEING 757-200 WINGLETS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-14
1,6489dd39cc5ce30f8f2edea7,WN3284:ATL:A:2023-06-14T04:20:00.000Z,2023-06-14T04:20:00.000Z,3284,J,Southwest Airlines,WN,7S8,BOEING 737-800,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-14
2,6489dd39cc5ce30f8f2edea8,LXJ387:FPR:A:2023-06-14T13:32:00.000Z,2023-06-14T13:32:00.000Z,387,F,Bombardier Business Jet Solutions,LXJ,E55P,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-14
3,6489dd39cc5ce30f8f2edea9,JLG533:INT:A:2023-06-14T13:32:00.000Z,2023-06-14T13:32:00.000Z,533,F,NaN,JLG,CJ3,CESSNA 525B CITATIONJET 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-14
4,6489dd39cc5ce30f8f2edead,JRE827:PBI:A:2023-06-14T14:12:00.000Z,2023-06-14T14:12:00.000Z,827,F,NaN,JRE,C5X,CESSNA 560XL CITATION EXCEL/XLS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393221,68934475441e5105a60c98cb,68934474cb3a8524eba15820,2025-08-06T16:17:00.000Z,NaN,Y,PVT,PVT,LJ4,???,N1904S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-06
393222,68934475441e5105a60c98cc,68934474cb3a8524eba15828,2025-08-06T13:35:00.000Z,NaN,Y,PVT,PVT,172,CESSNA 172,N3509Q,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-06
393223,68934475441e5105a60c98cd,68934475cb3a8524eba15830,2025-08-06T14:00:00.000Z,NaN,Y,PVT,PVT,E50P,???,N203SS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-06
393224,68934835441e5105a60c98ce,68934834cb3a8524eba15920,2025-08-06T16:29:00.000Z,NaN,Y,PVT,PVT,C172,CESSNA 172,N2475L,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-06
393225,689348ad441e5105a60c98cf,689348accb3a8524eba15954,2025-08-06T12:30:00.000Z,NaN,Y,PVT,PVT,C172,CESSNA 172,N3819Q,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-08-06

# Merge datasets

In [5]:
# Clean and convert flight number in df1
flights_df['flight_number_clean'] = flights_df['flight_number_clean'].astype(str)

# Convert df2 flight_number to string
extra_info_df['flight_number'] = extra_info_df['flight_number'].astype(str)
extra_info_df['Date'] = pd.to_datetime(extra_info_df['Date'])

# Merge on cleaned flight number and scheduled_date
merged_df = pd.merge(
    flights_df,
    extra_info_df,
    left_on=['Date', 'flight_number_clean'],
    right_on=['Date', 'flight_number'],
    how='inner'
)

merged_df

,Unnamed: 0,Date,Flight,Destination Airport,Airline,Boarded,Day_of_Week,Month,Day_of_Month,Destination Airport_encoded,...,baggage_belt_new,interfacePriority.baggage_belt_new_2,interfacePriority.baggage_belt_new_3,interfacePriority.baggage_belt_tues,baggage_belt_new_2,baggage_belt_new_3,baggage_belt_tues,interfacePriority.flight_stop_names,interfacePriority.flight_stop_codes,interfacePriority.country
0,0,2023-09-14,AA2679,DFW,AA,130,3,9,14,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2023-09-14,AA2679,DFW,AA,130,3,9,14,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2023-09-14,G41150,PIT,G4,155,3,9,14,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,2023-09-14,G4183,ABE,G4,152,3,9,14,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,2023-09-14,G4218,AVL,G4,144,3,9,14,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14011,12555,2025-07-20,WN4409,IND,WN,71,6,7,20,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14012,12556,2025-07-20,WN4605,MDW,WN,125,6,7,20,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14013,12557,2025-07-20,WN4606,STL,WN,75,6,7,20,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14014,12558,2025-07-20,XP306,HVN,XP,132,6,7,20,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14015,12559,2025-07-21,G41875,AVL,G4,113,0,7,21,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14016 entries, 0 to 14015
Columns: 239 entries, Unnamed: 0 to interfacePriority.country
dtypes: datetime64[ns](1), float64(107), int64(7), object(124)
memory usage: 25.6+ MB

In [7]:
merged_df.to_csv('SRQ_flights.csv', index=False)

In [9]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14016 entries, 0 to 14015
Columns: 239 entries, Unnamed: 0 to interfacePriority.country
dtypes: datetime64[ns](1), float64(107), int64(7), object(124)
memory usage: 25.6+ MB